apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-transform
  annotations:
    description: |
      Take the resources from a `crane-export` and generate JSON patches to
      remove
spec:
  params:
    - name: optional-flags
      type: string
      description: |
        Comma separated list of `flag-name=value` pairs. These flags with values
        will be passed into all plugins that are executed in the transform
        operation.
      default: "[]"
  steps:
    - name: crane-transform
      image: quay.io/djzager/crane-runner:alpha
      script: |
        crane transform \
          --ignored-patches-dir="$(workspaces.ignored-patches.path)" \
          --flags-file="$(workspaces.craneconfig.path)" \
          --optional-flags="$(params.optional-flags)" \
          --export-dir="$(workspaces.export.path)" \
          --transform-dir=$(workspaces.transform.path)

        find $(workspaces.transform.path)
        if [ "$(workspaces.ignored-patches.bound)" == "true" ]; then
          find $(workspaces.ignored-patches.path)
        fi
  workspaces:
    - name: export
      description: |
        This is the folder where the results of crane export were stored.
      mountPath: /var/crane/export
    - name: transform
      description: |
        This is the folder where we will store the results of crane transform.
      mountPath: /var/crane/transform
    - name: ignored-patches
      description: |
        This is the folder where the results of crane ignored-patches were stored.
      mountPath: /var/crane/ignored-patches
      optional: true
    - name: craneconfig
      description: |
        This is where we hold the configuration file for crane.
      mountPath: /var/crane/config
      optional: true
