apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kubectl-scale-down
  annotations:
    description: |
      Scale resource down using kubectl scale.
spec:
  params:
    - name: context
      type: string
      description: |
        Context to use when scaling down resources
      default: ""
    - name: namespace
      type: string
      description: |
        Namespace to use when scaling down resources
      default: ""
    - name: resource-type
      type: string
      description: |
        The resource type to be scaled down.
  steps:
    - name: kubectl-scale-down
      image: quay.io/konveyor/crane-runner:latest
      script: |
        kubectl scale --context "$(params.context)" --namespace "$(params.namespace)" --replicas=0 "$(params.resource-type)" --all
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/kubeconfig
  workspaces:
    - name: kubeconfig
      description: |
        The kubeconfig for accessing the source cluster.
