apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-kubeconfig-generator
  annotations:
    description: |
      This Task is responsible for taking a secret with keys `url` and `token`,
      logging into the cluster using `oc login`, renaming the context, and
      saving the result in the kubeconfig workspace.

      The idea is that subsequent Tasks in a Pipeline or PipelineRun could
      reference this task first to populate a kubeconfig based on cluster
      auth stored in a secret.
spec:
  params:
    - name: cluster-secret
      type: string
      description: |
        The name of the secret holding cluster API Server URL and Token.
    - name: context-name
      type: string
      description: |
        The name to give the context.
  steps:
    - name: crane-export
      image: quay.io/djzager/crane-runner:alpha
      script: |
        export KUBECONFIG=$(workspaces.kubeconfig.path)/kubeconfig

        set +x
        oc login --insecure-skip-tls-verify --server=$CLUSTER_URL --token=$CLUSTER_TOKEN
        set -x

        kubectl config rename-context "$(kubectl config current-context)" "$(params.context-name)"
      env:
        - name: CLUSTER_URL
          valueFrom:
            secretKeyRef:
              name: $(params.cluster-secret)
              key: url
        - name: CLUSTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.cluster-secret)
              key: token
  workspaces:
    - name: kubeconfig
      readOnly: false
      description: |
        Where the generated kubeconfig will be saved.
