apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-export
  annotations:
    migration.openshift.io/placeholder: "true"
    description: |
      Export all of the resources from a given cluster's namespace.
spec:
  params:
    - name: src-context
      type: string
      description: |
        The name of the context from kubeconfig representing the source
        cluster.

        You can get this information in your current environment using
        `kubectl config get-contexts` to describe your one or many
        contexts.
    - name: src-namespace
      type: string
      description: |
        The source cluster namespace from which to export resources.
  steps:
    - name: crane-export
      image: quay.io/konveyor/crane-runner:latest
      script: |
        /crane export \
          --context=$(params.src-context) \
          --namespace=$(params.src-namespace) \
          --export-dir=$(workspaces.export.path)

        # Do this so we have some breadcrumbs in case our demo blows up
        find $(workspaces.export.path)
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/config
  workspaces:
    - name: export
      description: |
        Directory where results of crane export will be stored for future use
        in other tasks.
      mountPath: /var/crane/export
    - name: kubeconfig
      description: |
        The kubeconfig for accessing the source cluster.
