apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-transfer-pvc
  annotations:
    migration.openshift.io/placeholder: "true"
    description: |
      Sync's a single PVC from source to destination cluster
spec:
  params:
    - name: src-context
      type: string
      description: |
        The name of the context from kubeconfig representing the source
        cluster.

        You can get this information in your current environment using
        `kubectl config get-contexts` to describe your one or many
        contexts.
    # TODO(djzager): Use this when we can provide a namespace mapping
    # - name: src-namespace
    #   type: string
    #   description: |
    #     The source cluster namespace in which pvc is synced.
    - name: dest-context
      type: string
      description: |
        The name of the context from kubeconfig representing the destination
        cluster.

        You can get this information in your current environment using
        `kubectl config get-contexts` to describe your one or many
        contexts.
    - name: dest-namespace
      type: string
      description: |
        The destination cluster namespace in which pvc is synced.
    - name: pvc-name
      type: string
      description: |
        The name of the pvc to be synced.
    - name: endpoint-type
      type: string
      description: |
        The name of the networking endpoint to be used for ingress traffic in the destination cluster
  steps:
    - name: crane-transfer-pvc
      image: quay.io/konveyor/crane-runner:latest
      script: |
        /crane transfer-pvc \
          --destination-context=$(params.dest-context) \
          --source-context=$(params.src-context) \
          --pvc-name $(params.pvc-name) \
          --pvc-namespace $(params.dest-namespace) \
          --endpoint $(params.endpoint-type)
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/config
  workspaces:
    - name: kubeconfig
      description: |
        The kubeconfig for accessing the source cluster.
