apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kubectl-scale-down
  annotations:
    migration.openshift.io/placeholder: "true"
    description: |
      Scale resource down using kubectl scale.
spec:
  params:
    - name: context
      type: string
      description: |
        Context to use when scaling down resources
    - name: namespace
      type: string
      description: |
        Namespace to use when scaling down resources
    - name: type-name-resource
      type: string
      description: |
        The resource to be scaled down in type/name format (ie. deployment/mysql or rc/foo)
  steps:
    - name: kubectl-scale-down
      image: quay.io/konveyor/crane-runner:latest
      script: |
        kubectl scale --context $(params.context) --namespace $(params.namespace) --replicas=0 $(params.type-name-resource)
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/config
  workspaces:
    - name: kubeconfig
      description: |
        The kubeconfig for accessing the source cluster.
